/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KekaSlider {
        "left": number;
        "maxValue": number;
        "minGap": number;
        "minValue": number;
        "right": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface KekaSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKekaSliderElement;
}
declare global {
    interface HTMLKekaSliderElement extends Components.KekaSlider, HTMLStencilElement {
    }
    var HTMLKekaSliderElement: {
        prototype: HTMLKekaSliderElement;
        new (): HTMLKekaSliderElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "keka-slider": HTMLKekaSliderElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface KekaSlider {
        "left"?: number;
        "maxValue"?: number;
        "minGap"?: number;
        "minValue"?: number;
        "onOnRangeChanged"?: (event: KekaSliderCustomEvent<number[]>) => void;
        "right"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "keka-slider": KekaSlider;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "keka-slider": LocalJSX.KekaSlider & JSXBase.HTMLAttributes<HTMLKekaSliderElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
